providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = []

[start]
cmd = "DIST_PATH=dist node backend/node_modules/.bin/tsx backend/index.ts"
