import { useEffect, type ReactNode } from 'react';
import { createPortal } from 'react-dom';
import type { AIProcessTraceEvent } from '../../types';
import { useI18n } from '../../lib/i18n';

export default function ProcessTrace({ events }: { events?: AIProcessTraceEvent[] }) {
  const { tr } = useI18n();
  if (!events?.length) return <p className="text-xs text-slate-400">{tr('Chưa có nhật ký. Hãy tạo lại kết quả.', 'No log yet. Regenerate the result.')}</p>;
  return <div className="divide-y divide-violet-100 rounded-xl border border-violet-100 overflow-hidden">{events.map((event, index) => <div key={event.id} className="p-4 bg-white"><div className="flex items-start gap-3"><span className={`w-6 h-6 rounded-full flex items-center justify-center shrink-0 text-[10px] font-bold ${event.status === 'completed' ? 'bg-emerald-100 text-emerald-700' : event.status === 'warning' ? 'bg-amber-100 text-amber-700' : 'bg-rose-100 text-rose-700'}`}>{index + 1}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="text-xs text-slate-800">{event.title}</b><span className="text-[9px] uppercase tracking-wider text-slate-400">{event.stage}</span></div><p className="text-[10px] text-slate-600 leading-relaxed mt-1 whitespace-pre-wrap">{event.detail}</p>{event.facts && <div className="flex flex-wrap gap-1.5 mt-2">{Object.entries(event.facts).map(([key, value]) => <span key={key} className="rounded-md border border-slate-200 bg-slate-50 px-2 py-1 text-[9px] text-slate-600"><b>{key}:</b> {String(value ?? 'n/a')}</span>)}</div>}{(event.sources?.length ?? 0) > 0 && <div className="flex flex-wrap gap-2 mt-2">{event.sources?.map((url, sourceIndex) => <a key={`${url}-${sourceIndex}`} href={url} target="_blank" rel="noreferrer" className="text-[9px] text-violet-700 underline hover:text-violet-900">Source {sourceIndex + 1}</a>)}</div>}</div></div></div>)}</div>;
}

export function ProcessTraceModal({ title, events, onClose, children }: { title: string; events?: AIProcessTraceEvent[]; onClose: () => void; children?: ReactNode }) {
  const { tr } = useI18n();
  useEffect(() => { const close = (event: KeyboardEvent) => event.key === 'Escape' && onClose(); window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, [onClose]);
  return createPortal(<div className="fixed inset-0 z-[110] bg-slate-950/60 backdrop-blur-sm p-3 sm:p-6 flex items-center justify-center" onMouseDown={event => event.target === event.currentTarget && onClose()} role="dialog" aria-modal="true" aria-label={title}><div className="codex-dark contents"><div className="w-full max-w-4xl max-h-[92dvh] rounded-2xl bg-white shadow-2xl border border-slate-200 flex flex-col overflow-hidden"><div className="flex items-start justify-between gap-3 px-4 sm:px-6 py-4 border-b border-slate-100"><div><div className="text-[10px] font-bold uppercase tracking-wider text-violet-700">{tr('Nhật ký hành động AI', 'AI action log')}</div><h3 className="text-sm font-bold text-slate-800 mt-1">{title}</h3><p className="text-[10px] text-slate-500 mt-1">{tr('Các hành động có thể kiểm chứng, không phải chain-of-thought nội bộ.', 'Verifiable actions, not private chain-of-thought.')}</p></div><button onClick={onClose} className="w-8 h-8 rounded-full bg-slate-100 hover:bg-slate-200 text-slate-500 text-lg" aria-label={tr('Đóng', 'Close')}>×</button></div><div className="flex-1 overflow-y-auto p-4 sm:p-6 space-y-5"><ProcessTrace events={events} />{children}</div></div></div></div>, document.body);
}
