import { useState, useMemo, useEffect, useRef } from 'react';
import { Check, LoaderCircle, Sparkles, X } from 'lucide-react';
import type { Article, AIModel, AppConfig, DocumentFile, EvidenceRef } from '../../types';
import { callAI } from '../../lib/aiService';
import { useI18n } from '../../lib/i18n';
import {
  collectStepDocs,
  buildActionPlanFingerprint,
  buildRoleSystemPrompt,
  buildStepDocumentPromptRules,
  describeBundle,
} from '../../lib/docContext';

function countWords(text: string) {
  return text.trim().split(/\s+/).filter(Boolean).length;
}

function calcReadability(text: string) {
  const sentences = text.split(/[.!?]+/).filter(s => s.trim().length > 3);
  const words = text.trim().split(/\s+/).filter(Boolean);
  if (!sentences.length || !words.length) return null;
  const avgWordsPerSentence = words.length / sentences.length;
  if (avgWordsPerSentence < 15) return { label: 'Rất dễ đọc', score: 95, color: 'text-emerald-600' };
  if (avgWordsPerSentence < 20) return { label: 'Dễ đọc', score: 80, color: 'text-emerald-500' };
  if (avgWordsPerSentence < 25) return { label: 'Trung bình', score: 65, color: 'text-amber-500' };
  return { label: 'Khó đọc', score: 40, color: 'text-red-500' };
}

function buildVerifiedOutlineContext(outline: NonNullable<Article['outline']>) {
  const evidenceRegistry: Record<string, EvidenceRef> = {};
  const evidenceIds = new Map<string, string>();
  const sections = outline.map(section => {
    const refs = (section.evidence ?? []).map(evidence => {
      const key = [evidence.role, evidence.source, evidence.quote].join('|');
      let id = evidenceIds.get(key);
      if (!id) {
        id = `ev-${evidenceIds.size + 1}`;
        evidenceIds.set(key, id);
        evidenceRegistry[id] = evidence;
      }
      return id;
    });
    return {
      heading: section.heading,
      level: section.level,
      notes: section.notes,
      rationale: section.rationale ?? '',
      keywords: section.keywords ?? [],
      searchIntent: section.searchIntent ?? '',
      evidenceRefs: refs,
      ruleRefs: section.ruleRefs ?? [],
    };
  });
  return { evidenceRegistry, sections };
}

function assessDraft(text: string, article: Article, targetWords: number): string[] {
  if (!text.trim()) return [];
  const normalized = text.toLocaleLowerCase();
  const words = countWords(text);
  const warnings: string[] = [];
  if (words < targetWords * 0.7) warnings.push(`Draft mới đạt ${words}/${targetWords} từ mục tiêu.`);
  const primaryKeyword = (article.keywords || '').split(',')[0]?.trim();
  if (primaryKeyword && !normalized.includes(primaryKeyword.toLocaleLowerCase())) warnings.push(`Chưa tìm thấy primary keyword “${primaryKeyword}”.`);
  const missingHeadings = (article.outline ?? []).filter(section =>
    section.heading.trim() && !normalized.includes(section.heading.trim().toLocaleLowerCase()),
  );
  if (missingHeadings.length) warnings.push(`Thiếu ${missingHeadings.length} heading từ outline Bước 2.`);
  return warnings;
}

interface Props {
  article: Article;
  config: AppConfig;
  files: DocumentFile[];
  model: AIModel;
  railwayUrl: string;
  onUpdate: (updates: Partial<Article>) => Promise<boolean>;
  onPrev: () => void;
  onToggleComplete: () => void;
  completionSaving: boolean;
}

export default function Step4Draft({ article, config, files, model, railwayUrl, onUpdate, onPrev, onToggleComplete, completionSaving }: Props) {
  const { tr, canonicalAIOutputInstruction } = useI18n();
  const bundle = useMemo(() => collectStepDocs(4, config, files), [config, files]);
  const documentPromptRules = useMemo(() => buildStepDocumentPromptRules(4, config, files), [config, files]);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  const editorRef = useRef<HTMLDivElement>(null);
  const autoGeneratedRef = useRef(false);
  const draftSaveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const pendingDraft = useRef<string | null>(null);
  const onUpdateRef = useRef(onUpdate);
  onUpdateRef.current = onUpdate;

  const draft = article.draft || '';
  const draftSourceFingerprint = useMemo(
    () => [
      buildActionPlanFingerprint(bundle), model.provider, model.id, 'step4-draft-v3-en',
      article.selectedCoreIdeaId, article.topic, article.angle,
      JSON.stringify(article.outline ?? []), article.tone, article.keywords, article.wordCount, documentPromptRules,
    ].join(':'),
    [article.angle, article.keywords, article.outline, article.selectedCoreIdeaId, article.tone, article.topic, article.wordCount, bundle, documentPromptRules, model.id, model.provider],
  );
  const wordCount = countWords(draft);
  const targetWords = article.wordCount || 1500;
  const readability = calcReadability(draft);
  const progress = Math.min(Math.round((wordCount / targetWords) * 100), 100);
  const draftIsStale = Boolean(draft) && article.draftSourceFingerprint !== draftSourceFingerprint;
  const draftWarnings = useMemo(() => assessDraft(draft, article, targetWords), [article, draft, targetWords]);

  // Keyword density check
  const keywordList = (article.keywords || '').split(',').map(k => k.trim().toLowerCase()).filter(Boolean);
  const draftLower = draft.toLowerCase();
  const keywordStats = keywordList.slice(0, 4).map(kw => ({
    keyword: kw,
    count: (draftLower.match(new RegExp(kw.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g')) || []).length,
    density: draft ? `${(((draftLower.match(new RegExp(kw.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g')) || []).length / Math.max(wordCount, 1)) * 100).toFixed(1)}%` : '0%',
  }));

  const handleGenerate = async (manual = false) => {
    if (!(article.outline && article.outline.length)) {
      setError('Bước 3 cần outline đã lưu từ Bước 2. Vui lòng quay lại Bước 2 và tạo hoặc lưu ít nhất một section.');
      return;
    }
    setGenerating(true);
    setError('');
    try {
      const verifiedOutline = buildVerifiedOutlineContext(article.outline || []);
      const contextQuery = [
        article.topic,
        article.angle,
        article.keywords,
        ...(article.outline ?? []).map(section => section.heading),
      ].filter(Boolean).join(' ');
      const maxTokens = Math.min(12_000, Math.max(2_500, Math.ceil(targetWords * 2.4)));

      const systemPrompt = buildRoleSystemPrompt(
        [
          canonicalAIOutputInstruction,
          'Viết bài hoàn chỉnh theo dàn bài và tài liệu được cấp.',
          '- Knowledge Base là nguồn dữ liệu duy nhất cho số liệu, dẫn chứng, thông tin sản phẩm. KHÔNG bịa dữ liệu.',
          '- Action Plan xác định định hướng nội dung và các mục bắt buộc.',
          '- Rules & Guidelines quyết định tone of voice, từ ngữ cấm, cấu trúc câu, quy tắc SEO. PHẢI tuân thủ tuyệt đối.',
          '- Khi dùng thông tin từ KB, nêu tự nhiên trong văn bản (không cần footnote).',
          '- Nếu KB không có dữ liệu cho một mục, viết mục đó ở dạng khung và ghi chú "[Cần bổ sung dữ liệu]".',
          '- Giữ nguyên đầy đủ heading và đúng thứ tự section của OUTLINE_STEP_3.',
          '- Evidence trong OUTLINE_STEP_3 đã được kiểm chứng; dùng đúng evidenceRefs cho section tương ứng, không bịa thêm số liệu.',
          '- Chỉ trả về nội dung bài viết hoàn chỉnh bằng Markdown, không thêm lời dẫn, nhật ký hoặc giải thích về quá trình viết.',
        ].join('\n'),
        documentPromptRules,
      );
      const userPrompt = [
        `TÀI LIỆU STEP 4 (${describeBundle(bundle)}):`,
        bundle.totalCount
          ? 'Railway sẽ nạp các đoạn tài liệu liên quan nhất trong tài liệu được cấp quyền cho Bước 3 từ Supabase.'
          : 'Bước 3 không có tài liệu riêng; dùng evidence đã kiểm chứng trong outline Bước 2 làm nguồn.',
        '',
        'THÔNG TIN BÀI VIẾT:',
        `- Chủ đề: "${article.topic}"`,
        `- Angle: ${article.angle || ''}`,
        `- Độc giả: ${article.targetAudience || ''}`,
        `- Giọng văn: ${article.tone || ''}`,
        `- Từ khóa: ${article.keywords || ''}`,
        `- Số từ mục tiêu: ~${targetWords}`,
        '',
        'OUTLINE_STEP_3 VÀ EVIDENCE ĐÃ KIỂM CHỨNG:',
        JSON.stringify(verifiedOutline),
        '',
        'Yêu cầu: Viết bài hoàn chỉnh theo dàn bài trên, tuân thủ toàn bộ Rules & Guidelines.',
      ].join('\n');

      const res = await callAI({
        articleId: article.id,
        model,
        railwayUrl,
        prompt: userPrompt,
        systemPrompt,
        stepNumber: 4,
        bypassCache: manual,
        maxTokens,
        temperature: 0.2,
        contextQuery,
        skipDocumentContext: !bundle.totalCount,
      });
      if (!res.content.trim()) throw new Error('AI trả về draft rỗng. Kết quả cũ vẫn được giữ nguyên.');
      const saved = await onUpdate({
        draft: res.content,
        draftSourceFingerprint,
        draftScannedAt: res.servedAt ?? res.generatedAt ?? new Date().toISOString(),
      });
      if (!saved) throw new Error('Draft Bước 3 chưa được lưu vào Supabase.');
      if (editorRef.current) editorRef.current.innerText = res.content;
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setGenerating(false);
    }
  };

  // Auto-generate draft on step entry when no cached draft exists.
  // Requires an outline from Step 3; only runs once per mount.
  useEffect(() => {
    if (autoGeneratedRef.current) return;
    if (article.draft) return;
    if (!(article.outline && article.outline.length)) return;
    autoGeneratedRef.current = true;
    handleGenerate(false);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [article.outline?.length, article.draft]);

  const handleEditorInput = () => {
    if (editorRef.current) {
      pendingDraft.current = editorRef.current.innerText;
      if (draftSaveTimer.current) clearTimeout(draftSaveTimer.current);
      draftSaveTimer.current = setTimeout(() => {
        if (pendingDraft.current !== null) onUpdateRef.current({ draft: pendingDraft.current });
        pendingDraft.current = null;
        draftSaveTimer.current = null;
      }, 700);
    }
  };

  useEffect(() => () => {
    if (draftSaveTimer.current) clearTimeout(draftSaveTimer.current);
    if (pendingDraft.current !== null) onUpdateRef.current({ draft: pendingDraft.current });
  }, []);

  const handleCopy = () => {
    navigator.clipboard.writeText(draft);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="minimal-step h-full flex flex-col gap-4 animate-fade-in-up">
      <div className="minimal-step-shell bg-[#ebedf3] rounded-3xl p-1.5 shadow-sm border border-slate-200/60 flex-1 flex flex-col min-h-0">
        <div className="flex-1 flex flex-col lg:flex-row gap-3 p-2 sm:p-3 min-h-0 overflow-y-auto lg:overflow-hidden">

          {/* Editor panel */}
          <div className="draft-editor flex-1 bg-white rounded-2xl flex flex-col shadow-sm min-w-0 min-h-[55dvh] lg:min-h-0">
            {/* Editor toolbar */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 px-3 sm:px-4 py-2.5 border-b border-slate-100">
              <div className="min-w-0">
                <h2 className="text-sm font-bold text-slate-800">{tr('Bước 3: Bản nháp & Kiểm tra', 'Step 3: First Draft & Audit')}</h2>
                <p className="text-[10px] text-slate-400">{article.title || 'Bài viết mới'}</p>
              </div>
              <div className="flex items-center gap-2 shrink-0">
                <button
                  onClick={() => handleGenerate(Boolean(draft))}
                  disabled={generating}
                  className="bg-indigo-600 hover:bg-indigo-700 disabled:opacity-60 text-white text-xs font-bold px-3 py-1.5 rounded-xl transition-all flex items-center space-x-1.5"
                >
                  {generating ? (
                    <>
                      <LoaderCircle className="app-icon animate-spin" aria-hidden="true" />
                      <span>{tr('Đang viết...', 'Writing...')}</span>
                    </>
                    ) : <><Sparkles className="app-icon" aria-hidden="true" /><span>{draft ? tr('Viết lại', 'Rewrite') : tr('AI Viết Draft', 'AI Draft')}</span></>}
                </button>
                <button
                  onClick={handleCopy}
                  disabled={!draft}
                  className="bg-slate-100 hover:bg-slate-200 disabled:opacity-40 text-slate-700 text-xs font-semibold px-3 py-1.5 rounded-xl transition-all"
                >
                  {copied ? tr('✓ Đã copy', '✓ Copied') : 'Copy'}
                </button>
              </div>
            </div>

            {error && (
              <div className="mx-3 sm:mx-4 mt-3 rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700">
                {error}
              </div>
            )}

            {draftIsStale && !generating && (
              <div className="mx-3 sm:mx-4 mt-3 rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-700">
                Outline, tài liệu, prompting rules hoặc model đã thay đổi. Draft đã lưu vẫn được giữ nguyên; chỉ cập nhật khi bạn nhấn “Viết lại”.
              </div>
            )}

            {draftWarnings.length > 0 && !generating && (
              <div className="mx-3 sm:mx-4 mt-3 rounded-xl border border-sky-200 bg-sky-50 px-3 py-2 text-xs text-sky-800">
                <div className="font-semibold mb-1">Kiểm tra nhanh — draft vẫn đã được lưu:</div>
                <ul className="list-disc pl-4 space-y-0.5">
                  {draftWarnings.map(warning => <li key={warning}>{warning}</li>)}
                </ul>
              </div>
            )}

            {/* Draft editor */}
            <div className="flex-1 overflow-y-auto p-3 sm:p-5">
              {generating ? (
                <div className="space-y-3">
                  {[...Array(12)].map((_, i) => (
                    <div key={i} className="ai-loading h-4" style={{ width: `${60 + Math.random() * 40}%` }} />
                  ))}
                </div>
              ) : (
                <div
                  ref={editorRef}
                  contentEditable
                  suppressContentEditableWarning
                  onInput={handleEditorInput}
                  data-placeholder={tr("Nhấn 'AI Viết Draft' để tạo nội dung, hoặc bắt đầu viết thủ công...", "Click 'AI Draft' to generate content, or start writing manually...")}
                  className="prose-editor min-h-full whitespace-pre-wrap"
                >
                  {draft || ''}
                </div>
              )}
            </div>

            {/* Word count bar */}
            <div className="px-5 py-2.5 border-t border-slate-100">
              <div className="flex items-center justify-between text-[11px] text-slate-500 mb-1.5">
                <span className="font-mono font-semibold">{wordCount.toLocaleString()} / {targetWords.toLocaleString()} từ</span>
                <span>{progress}% {tr('hoàn thành', 'complete')}</span>
              </div>
              <div className="h-1 bg-slate-100 rounded-full overflow-hidden">
                <div
                  className={`h-full rounded-full transition-all ${progress >= 100 ? 'bg-emerald-500' : progress >= 70 ? 'bg-blue-500' : 'bg-amber-400'}`}
                  style={{ width: `${progress}%` }}
                />
              </div>
            </div>
          </div>

          {/* Audit panel */}
          <div className="w-full lg:w-60 grid grid-cols-1 sm:grid-cols-2 lg:flex lg:flex-col gap-3 shrink-0">
            {/* Readability */}
            <div className="bg-white rounded-2xl p-4 shadow-sm space-y-3">
              <h3 className="text-xs font-bold text-slate-800">{tr('Phân tích nội dung', 'Content analysis')}</h3>
              <div className="space-y-2.5">
                <div>
                  <div className="flex justify-between text-[11px] mb-1">
                    <span className="text-slate-500 font-medium">{tr('Độ dễ đọc', 'Readability')}</span>
                    <span className={`font-bold ${readability?.color || 'text-slate-400'}`}>{readability
                      ? tr(readability.label, readability.score >= 90 ? 'Very easy' : readability.score >= 75 ? 'Easy' : readability.score >= 60 ? 'Medium' : 'Difficult')
                      : '—'}</span>
                  </div>
                  <div className="h-1.5 bg-slate-100 rounded-full overflow-hidden">
                    <div className="h-full bg-emerald-500 rounded-full transition-all" style={{ width: `${readability?.score || 0}%` }} />
                  </div>
                </div>

                <div className="flex justify-between text-[11px]">
                  <span className="text-slate-500">{tr('Số từ', 'Words')}</span>
                  <span className="font-mono font-bold text-slate-700">{wordCount.toLocaleString()}</span>
                </div>
                <div className="flex justify-between text-[11px]">
                  <span className="text-slate-500">{tr('Số đoạn', 'Paragraphs')}</span>
                  <span className="font-mono font-bold text-slate-700">{draft.split('\n\n').filter(p => p.trim()).length}</span>
                </div>
                <div className="flex justify-between text-[11px]">
                  <span className="text-slate-500">{tr('Số ký tự', 'Characters')}</span>
                  <span className="font-mono font-bold text-slate-700">{draft.length.toLocaleString()}</span>
                </div>
              </div>
            </div>

            {/* SEO Checklist */}
            <div className="bg-white rounded-2xl p-4 shadow-sm space-y-3">
              <h3 className="text-xs font-bold text-slate-800">SEO Checklist</h3>
              <div className="space-y-2">
                {[
                  { label: 'Tiêu đề có từ khóa', pass: article.topic ? keywordList.some(k => article.topic!.toLowerCase().includes(k)) : false },
                  { label: 'Độ dài >= 800 từ', pass: wordCount >= 800 },
                  { label: 'Độ dài >= mục tiêu', pass: wordCount >= targetWords * 0.9 },
                  { label: 'Có headings (H2/H3)', pass: draft.includes('##') || (article.outline || []).length > 0 },
                  { label: 'Từ khóa xuất hiện trong bài', pass: keywordList.some(k => draftLower.includes(k)) },
                ].map(item => (
                  <div key={item.label} className="flex items-center gap-2">
                    <div className={`w-4 h-4 rounded-full flex items-center justify-center shrink-0 ${item.pass ? 'bg-emerald-100 text-emerald-600' : 'bg-slate-100 text-slate-400'}`}>
                      {item.pass ? <Check className="app-icon" aria-hidden="true" /> : <X className="app-icon" aria-hidden="true" />}
                    </div>
                    <span className={`text-[11px] ${item.pass ? 'text-slate-700' : 'text-slate-400'}`}>{item.label}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Keyword density */}
            {keywordStats.length > 0 && (
              <div className="bg-white rounded-2xl p-4 shadow-sm space-y-3">
                <h3 className="text-xs font-bold text-slate-800">{tr('Mật độ từ khóa', 'Keyword density')}</h3>
                <div className="space-y-2">
                  {keywordStats.map(kw => (
                    <div key={kw.keyword}>
                      <div className="flex justify-between text-[11px] mb-0.5">
                        <span className="text-slate-600 font-medium truncate max-w-[120px]">{kw.keyword}</span>
                        <span className="font-mono text-slate-700 font-bold">{kw.density}</span>
                      </div>
                      <div className="h-1 bg-slate-100 rounded-full overflow-hidden">
                        <div
                          className="h-full bg-indigo-400 rounded-full"
                          style={{ width: `${Math.min(parseFloat(kw.density) * 20, 100)}%` }}
                        />
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Export */}
            <div className="bg-white rounded-2xl p-4 shadow-sm space-y-2">
              <h3 className="text-xs font-bold text-slate-800">{tr('Xuất bài viết', 'Export article')}</h3>
              <button
                onClick={handleCopy}
                disabled={!draft}
                className="w-full py-2 bg-slate-900 hover:bg-slate-800 disabled:opacity-40 text-white text-xs font-semibold rounded-xl transition-all"
              >
                {copied ? tr('✓ Đã copy', '✓ Copied') : tr('Copy toàn bộ nội dung', 'Copy all content')}
              </button>
              <button
                disabled={!draft}
                onClick={() => {
                  const blob = new Blob([draft], { type: 'text/plain' });
                  const url = URL.createObjectURL(blob);
                  const a = document.createElement('a');
                  a.href = url;
                  a.download = `${(article.title || 'bai-viet').replace(/\s+/g, '-')}.txt`;
                  a.click();
                  URL.revokeObjectURL(url);
                }}
                className="w-full py-2 bg-slate-100 hover:bg-slate-200 disabled:opacity-40 text-slate-700 text-xs font-semibold rounded-xl transition-all"
              >
                {tr('Tải xuống .txt', 'Download .txt')}
              </button>
            </div>
          </div>
        </div>
      </div>

      <div className="flex justify-between gap-2 shrink-0">
        <button onClick={onPrev} className="bg-white hover:bg-slate-50 border border-slate-200 text-slate-700 font-semibold text-xs py-2.5 px-3 sm:px-5 rounded-2xl shadow-sm transition-all">
          {tr('← Quay lại Outline', '← Back to Outline')}
        </button>
        <button
          onClick={onToggleComplete}
          disabled={!draft || completionSaving}
          className={`${article.status === 'done' ? 'bg-white hover:bg-slate-50 border border-emerald-300 text-emerald-700' : 'bg-emerald-600 hover:bg-emerald-700 text-white'} disabled:opacity-40 disabled:cursor-not-allowed font-semibold text-xs py-2.5 px-3 sm:px-6 rounded-2xl shadow-sm transition-all`}
        >
          {completionSaving ? 'Đang lưu...' : article.status === 'done' ? '↺ Mở lại bài viết' : '✓ Đánh dấu hoàn thành'}
        </button>
      </div>
    </div>
  );
}
