/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "avflicunyavlfnsmpzxy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2ZmxpY3VueWF2bGZuc21wenh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU0ODEyNjMsImV4cCI6MjEwMTA1NzI2M30._Pj2m-BPObqWXQ85P1jAJGqn9-UVIm74dpchO94XlJs"