import { useState } from 'react';
import type { Article } from '../types';
import { useI18n } from '../lib/i18n';
import { buildBatchZip } from '../lib/zipExport';

interface Props { articles: Article[]; onOpen: (id: string) => void; onStart: () => Promise<void>; onPause: () => Promise<void>; onRetry: (id: string) => Promise<void> }
function download(article: Article) { const blob = new Blob([article.draft ?? ''], { type: 'text/markdown;charset=utf-8' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${(article.topic || article.title).replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '') || 'article'}.md`; anchor.click(); URL.revokeObjectURL(url); }

export default function BatchActivity({ articles, onOpen, onStart, onPause, onRetry }: Props) {
  const { tr } = useI18n();
  const [action, setAction] = useState<string | null>(null);
  const complete = articles.filter(article => article.batchStatus === 'completed' || article.draft?.trim()).length;
  const failed = articles.filter(article => article.batchStatus === 'failed').length;
  const running = articles.some(article => article.batchStatus === 'running');
  const paused = !running && articles.some(article => article.batchStatus === 'paused');
  const totalTokens = articles.reduce((sum, article) => sum + Object.values(article.aiUsageByStep ?? {}).flat().reduce((inner, call) => inner + call.totalTokens, 0), 0);
  const usage = articles.flatMap(article => Object.values(article.aiUsageByStep ?? {}).flat());
  const knownCost = usage.reduce((sum, call) => sum + Number(call.costUsd ?? 0), 0);
  const hasUnknownCost = usage.some(call => call.costUsd == null);
  const act = async (name: string, callback: () => Promise<void>) => { setAction(name); try { await callback(); } finally { setAction(null); } };
  const downloadAll = () => { const blob = buildBatchZip(articles); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `comparison-seo-${articles[0]?.activityId ?? 'batch'}.zip`; anchor.click(); URL.revokeObjectURL(url); };

  return <main className="flex-1 overflow-y-auto p-4 md:p-6"><div className="mx-auto max-w-5xl space-y-4">
    <div className="rounded-3xl bg-slate-900 p-5 text-white"><div className="text-[10px] font-bold uppercase tracking-[.2em] text-indigo-300">Comparison / SEO batch</div><div className="mt-2 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-xl font-bold">{complete}/{articles.length} {tr('bài hoàn tất', 'articles completed')}</h1><p className="mt-1 text-xs text-slate-300">{totalTokens.toLocaleString()} tokens · ${knownCost.toFixed(4)}{hasUnknownCost ? '+' : ''} · {failed} {tr('lỗi', 'failed')} · concurrency 2</p></div><div className="flex flex-wrap gap-2">{running ? <button disabled={Boolean(action)} onClick={() => act('pause', onPause)} className="rounded-xl border border-slate-600 px-3 py-2 text-xs font-bold">{action === 'pause' ? '…' : tr('Tạm dừng', 'Pause')}</button> : complete < articles.length && <button disabled={Boolean(action)} onClick={() => act('start', onStart)} className="rounded-xl bg-indigo-500 px-3 py-2 text-xs font-bold">{action === 'start' ? '…' : paused ? tr('Tiếp tục', 'Resume') : tr('Chạy batch', 'Run batch')}</button>}<button disabled={!complete} onClick={downloadAll} className="rounded-xl bg-white px-3 py-2 text-xs font-bold text-slate-900 disabled:opacity-40">{tr('Tải ZIP', 'Download ZIP')}</button></div></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-700"><div className="h-full bg-emerald-400 transition-all" style={{ width: `${articles.length ? complete / articles.length * 100 : 0}%` }}/></div></div>
    <div className="grid gap-3 sm:grid-cols-2">{articles.map((article, index) => { const status = article.batchStatus ?? 'queued'; return <div key={article.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="text-[10px] font-bold uppercase text-indigo-600">#{index + 1} · {status} · Step {Math.max(1, article.currentStep - 1)}/3</div><h2 className="mt-1 line-clamp-2 text-sm font-bold text-slate-800">{article.topic || article.title}</h2></div><span className={`h-2.5 w-2.5 rounded-full ${status === 'completed' ? 'bg-emerald-500' : status === 'failed' ? 'bg-red-500' : status === 'running' ? 'bg-blue-500 animate-pulse' : status === 'paused' ? 'bg-amber-400' : 'bg-slate-300'}`} /></div>{article.batchError && <div className="mt-3 rounded-xl border border-red-100 bg-red-50 p-2 text-[10px] text-red-700">{article.batchError}</div>}<div className="mt-4 flex gap-2"><button onClick={() => onOpen(article.id)} className="flex-1 rounded-xl bg-slate-900 px-3 py-2 text-[11px] font-bold text-white">{tr('Mở pipeline', 'Open pipeline')}</button>{status === 'failed' && <button disabled={Boolean(action)} onClick={() => act(article.id, () => onRetry(article.id))} className="rounded-xl border border-red-200 px-3 py-2 text-[11px] font-bold text-red-600">{tr('Thử lại', 'Retry')}</button>}<button disabled={!article.draft?.trim()} onClick={() => download(article)} className="rounded-xl border border-slate-200 px-3 py-2 text-[11px] font-bold text-slate-600 disabled:opacity-40">{tr('Tải bài', 'Download')}</button></div></div>; })}</div>
  </div></main>;
}
